services:
  db:
    image: postgres:15
    container_name: bankcards-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: bankcardsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - bankcards_db_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bankcardsdb -h localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: bankcards-app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankcardsdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10

volumes:
  bankcards_db_data:
